application: gopher-web
version: 1
runtime: go
api_version: go1

handlers:
- url: /
  static_files: app/index.html
  upload: app/index.html
- url: /css
  static_dir: app/css
- url: /img
  static_dir: app/img
- url: /js
  static_dir: app/js
- url: /lib
  static_dir: app/lib
- url: /partials
  static_dir: app/partials
- url: /favicon\.ico
  static_files: app/img/favicon.ico
  upload: app/img/favicon\.ico
- url: /api/.*
  script: _go_app
- url: /admin/.*
  script: _go_app
